server:
  port: 10086

eureka:
  client:
    service-url:
      defaultZone: http://192.168.6.150:10010/eureka/

spring:
  application:
    name: exception-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: exception-transfer
          uri: lb://exception-transfer
          predicates:
            - Path=/transfer/** #断言,路径相匹配的进行路由
          filters:
            - RewritePath=/transfer/(?<segment>.*), /$\{segment}

        - id: exception-manager
          uri: lb://exception-manager
          predicates:
            - Path=/manager/**
          filters:
            - RewritePath=/manager/(?<segment>.*), /$\{segment}

        - id: exception-dashboard
          uri: lb://exception-dashboard
          predicates:
            - Path=/dashboard/**
          filters:
            - RewritePath=/dashboard/(?<segment>.*), /$\{segment}

