server:
  port: 10010
spring:
  application:
    name: exception-eureka

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: 192.168.6.174
#    prefer-ip-address: true
feign:
  client:
    config:
      dashboard:
        connect-timeout: 5000
        read-timeout: 10000
      manager:
        connect-timeout: 5000
        read-timeout: 10000