apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exception-transfer
  name: exception-transfer
  namespace: exception-$BRANCH_NAME   #一定要写名称空间
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: exception-transfer
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: exception-transfer
    spec:
      imagePullSecrets:
        - name: aliyun-docker-hub  #提前在项目下配置访问阿里云的账号密码
      containers:
        - image: $REGISTRY/$ALIYUNHUB_NAMESPACE/exception-transfer:$BRANCH_NAME-$BUILD_NUMBER-SNAPSHOT
 #         readinessProbe:
 #           httpGet:
 #             path: /actuator/health
 #             port: 8080
 #           timeoutSeconds: 10
 #           failureThreshold: 30
 #           periodSeconds: 5
          imagePullPolicy: Always
          args:
            - "--spring.profiles.active=$BRANCH_NAME"
          name: app
          ports:
            - containerPort: 9997
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: exception-transfer
  name: exception-transfer
  namespace: exception-$BRANCH_NAME
spec:
  ports:
    - name: http
      port: 9997
      protocol: TCP
      targetPort: 9997
  selector:
    app: exception-transfer
  sessionAffinity: None
  type: ClusterIP