server:
  port: 9997
#  address: 0.0.0.0
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  application:
    name: exception-transfer
  main:
    allow-bean-definition-overriding: true
  # database
  redis:
    host: 192.168.6.194
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://192.168.6.174:10010/eureka/

feign:
  client:
    config:
      dashboard:
        connect-timeout: 5000
        read-timeout: 10000
      manager:
        connect-timeout: 5000
        read-timeout: 10000