server:
  port: 9997
  address: 0.0.0.0
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  application:
    name: exception-transfer
  main:
    allow-bean-definition-overriding: true
  # database
  redis:
    host: 127.0.0.1
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka/
