server:
  port: 9998
#  address: 0.0.0.0
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  application:
    name: exception-manager
  main:
    allow-bean-definition-overriding: true
  # redis
  redis:
    host: 192.168.6.194
    port: 6379
  # database
  datasource:
    url: jdbc:postgresql://192.168.6.194:5432/dev
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 10
      pool-prepared-statements: true
      max-open-prepared-statements: 100
  # elasticsearch
  data:
    elasticsearch:
      host: 192.168.6.174
      port: 9200
  #kafka配置
  kafka:
    #这里改为你的kafka服务器ip和端口号
    bootstrap-servers: 192.168.6.174:9092
    #=============== producer  =======================
    producer:
      #如果该值大于零时，表示启用重试失败的发送次数
      retries: 0
      #每当多个记录被发送到同一分区时，生产者将尝试将记录一起批量处理为更少的请求，默认值为16384(单位字节)
      batch-size: 16384
      #生产者可用于缓冲等待发送到服务器的记录的内存总字节数，默认值为3355443
      buffer-memory: 33554432
      #key的Serializer类，实现类实现了接口org.apache.kafka.common.serialization.Serializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #value的Serializer类，实现类实现了接口org.apache.kafka.common.serialization.Serializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone: http://192.168.6.174:10010/eureka/
feign:
  client:
    config:
      dashboard:
        connect-timeout: 5000
        read-timeout: 10000
      manager:
        connect-timeout: 5000
        read-timeout: 10000